name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker Image
        run: |
          docker build -t demo-app:${{ github.sha }} .
      #
      - name: Push Docker Image to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker tag demo-app:${{ github.sha }} ${{ secrets.ACR_NAME }}.azurecr.io/demo-app:${{ github.sha }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/demo-app:${{ github.sha }}